// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"

class Vtop__Syms;
class Vtop___024unit;
class Vtop_CarrySaveAdder;


class Vtop___024root final : public VerilatedModule {
  public:
    // CELLS
    Vtop___024unit* __PVT____024unit;
    Vtop_CarrySaveAdder* __PVT__top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder;
    Vtop_CarrySaveAdder* __PVT__top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_1;
    Vtop_CarrySaveAdder* __PVT__top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_2;
    Vtop_CarrySaveAdder* __PVT__top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_3;
    Vtop_CarrySaveAdder* __PVT__top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_4;
    Vtop_CarrySaveAdder* __PVT__top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_5;
    Vtop_CarrySaveAdder* __PVT__top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_6;
    Vtop_CarrySaveAdder* __PVT__top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_7;
    Vtop_CarrySaveAdder* __PVT__top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_8;
    Vtop_CarrySaveAdder* __PVT__top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_9;
    Vtop_CarrySaveAdder* __PVT__top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_10;
    Vtop_CarrySaveAdder* __PVT__top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_11;
    Vtop_CarrySaveAdder* __PVT__top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_12;
    Vtop_CarrySaveAdder* __PVT__top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_13;
    Vtop_CarrySaveAdder* __PVT__top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_14;
    Vtop_CarrySaveAdder* __PVT__top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_15;
    Vtop_CarrySaveAdder* __PVT__top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_16;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_IN8(io_timer,0,0);
        VL_IN8(io_soft,0,0);
        VL_IN8(io_extern,0,0);
        VL_OUT8(io_flush,0,0);
        VL_OUT8(io_stall,0,0);
        VL_OUT8(io_bputake,0,0);
        VL_OUT8(io_romaddrvalid,0,0);
        VL_OUT8(io_romaddrready,0,0);
        VL_OUT8(io_romdatavalid,0,0);
        VL_OUT8(io_romdataready,0,0);
        VL_OUT8(io_ifaddrvalid,0,0);
        VL_OUT8(io_ifaddrready,0,0);
        VL_OUT8(io_ifdatavalid,0,0);
        VL_OUT8(io_ifdataready,0,0);
        CData/*0:0*/ top__DOT__core__DOT__ID_io_read2_en;
        CData/*0:0*/ top__DOT__core__DOT__ID_EX_io_stallNext;
        CData/*0:0*/ top__DOT__core__DOT__EX_io_ex_o_load;
        CData/*0:0*/ top__DOT__core__DOT__resoler_io_loadflag;
        CData/*0:0*/ top__DOT__core__DOT__arbiter_io_selectedMaster_master_arready;
        CData/*0:0*/ top__DOT__core__DOT__arbiter_io_selectedMaster_master_arvalid;
        CData/*0:0*/ top__DOT__core__DOT__arbiter_io_selectedMaster_master_rready;
        CData/*0:0*/ top__DOT__core__DOT__arbiter_io_selectedMaster_master_rvalid;
        CData/*0:0*/ top__DOT__core__DOT__fetch__DOT__bpu_io_inst_valid_i;
        CData/*1:0*/ top__DOT__core__DOT__fetch__DOT__state;
        CData/*0:0*/ top__DOT__core__DOT__fetch__DOT__ar_hs;
        CData/*0:0*/ top__DOT__core__DOT__fetch__DOT__r_hs;
        CData/*0:0*/ top__DOT__core__DOT__fetch__DOT___T_1;
        CData/*0:0*/ top__DOT__core__DOT__fetch__DOT___T_3;
        CData/*0:0*/ top__DOT__core__DOT__fetch__DOT___T_5;
        CData/*6:0*/ top__DOT__core__DOT__fetch__DOT__bpu__DOT__opcode;
        CData/*0:0*/ top__DOT__core__DOT__fetch__DOT__bpu__DOT____VdfgTmp_hfc59af28__0;
        CData/*0:0*/ top__DOT__core__DOT__IF_ID__DOT__ff_valid;
        CData/*0:0*/ top__DOT__core__DOT__IF_ID__DOT__ff_bpu_take;
        CData/*0:0*/ top__DOT__core__DOT__IF_ID__DOT__ff_misaligned;
        CData/*4:0*/ top__DOT__core__DOT__ID__DOT__rd;
        CData/*4:0*/ top__DOT__core__DOT__ID__DOT__rs1;
        CData/*4:0*/ top__DOT__core__DOT__ID__DOT__rs2;
        CData/*0:0*/ top__DOT__core__DOT__ID__DOT___T_152;
        CData/*0:0*/ top__DOT__core__DOT__ID__DOT___T_170;
        CData/*0:0*/ top__DOT__core__DOT__ID__DOT___T_187;
        CData/*0:0*/ top__DOT__core__DOT__ID__DOT__regEn1;
        CData/*0:0*/ top__DOT__core__DOT__ID__DOT___T_228;
        CData/*0:0*/ top__DOT__core__DOT__ID__DOT___T_245;
        CData/*0:0*/ top__DOT__core__DOT__ID__DOT___T_275;
        CData/*0:0*/ top__DOT__core__DOT__ID__DOT___T_292;
        CData/*3:0*/ top__DOT__core__DOT__ID__DOT___T_325;
        CData/*3:0*/ top__DOT__core__DOT__ID__DOT___T_340;
        CData/*3:0*/ top__DOT__core__DOT__ID__DOT___T_355;
        CData/*3:0*/ top__DOT__core__DOT__ID__DOT__aluSrc1;
        CData/*3:0*/ top__DOT__core__DOT__ID__DOT___T_388;
        CData/*3:0*/ top__DOT__core__DOT__ID__DOT___T_403;
        CData/*3:0*/ top__DOT__core__DOT__ID__DOT___T_418;
        CData/*3:0*/ top__DOT__core__DOT__ID__DOT__aluSrc2;
        CData/*3:0*/ top__DOT__core__DOT__ID__DOT___T_441;
        CData/*3:0*/ top__DOT__core__DOT__ID__DOT___T_456;
        CData/*3:0*/ top__DOT__core__DOT__ID__DOT___T_471;
        CData/*2:0*/ top__DOT__core__DOT__ID__DOT___T_528;
        CData/*2:0*/ top__DOT__core__DOT__ID__DOT__branchOp;
        CData/*3:0*/ top__DOT__core__DOT__ID__DOT___T_557;
        CData/*3:0*/ top__DOT__core__DOT__ID__DOT___T_572;
        CData/*3:0*/ top__DOT__core__DOT__ID__DOT___T_587;
        CData/*2:0*/ top__DOT__core__DOT__ID__DOT___T_628;
    };
    struct {
        CData/*2:0*/ top__DOT__core__DOT__ID__DOT___T_643;
        CData/*2:0*/ top__DOT__core__DOT__ID__DOT__csrOp;
        CData/*3:0*/ top__DOT__core__DOT__ID__DOT___T_678;
        CData/*3:0*/ top__DOT__core__DOT__ID__DOT___T_693;
        CData/*3:0*/ top__DOT__core__DOT__ID__DOT___T_708;
        CData/*3:0*/ top__DOT__core__DOT__ID__DOT___T_731;
        CData/*3:0*/ top__DOT__core__DOT__ID__DOT___T_746;
        CData/*3:0*/ top__DOT__core__DOT__ID__DOT___T_761;
        CData/*0:0*/ top__DOT__core__DOT__ID__DOT__branchteke;
        CData/*0:0*/ top__DOT__core__DOT__ID__DOT__addrFault;
        CData/*2:0*/ top__DOT__core__DOT__ID__DOT__csrActOp;
        CData/*0:0*/ top__DOT__core__DOT__ID__DOT____VdfgTmp_hc515ad56__0;
        CData/*3:0*/ top__DOT__core__DOT__ID_EX__DOT__ff_aluOp;
        CData/*3:0*/ top__DOT__core__DOT__ID_EX__DOT__ff_mduOp;
        CData/*3:0*/ top__DOT__core__DOT__ID_EX__DOT__ff_lsuOp;
        CData/*0:0*/ top__DOT__core__DOT__ID_EX__DOT__ff_regWen;
        CData/*4:0*/ top__DOT__core__DOT__ID_EX__DOT__ff_regWaddr;
        CData/*2:0*/ top__DOT__core__DOT__ID_EX__DOT__ff_csrOp;
        CData/*0:0*/ top__DOT__core__DOT__ID_EX__DOT__ff_csren;
        CData/*3:0*/ top__DOT__core__DOT__ID_EX__DOT__ff_excType;
        CData/*0:0*/ top__DOT__core__DOT__ID_EX__DOT___T_3;
        CData/*0:0*/ top__DOT__core__DOT__EX__DOT__mdu_io_valid;
        CData/*0:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__div_io_en;
        CData/*0:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__div_io_flush;
        CData/*0:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mulEn;
        CData/*0:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT___T_24;
        CData/*0:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__hiRem;
        CData/*0:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT___T_41;
        CData/*0:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__lhsSigned;
        CData/*0:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__isOpr1Neg;
        CData/*0:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__isOpr2Neg;
        CData/*0:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__isAnsNeg;
        CData/*0:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT___T_62;
        CData/*2:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__boothCode_1;
        CData/*2:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__boothCode_2;
        CData/*2:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__boothCode_3;
        CData/*2:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__boothCode_4;
        CData/*2:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__boothCode_5;
        CData/*2:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__boothCode_6;
        CData/*2:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__boothCode_7;
        CData/*2:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__boothCode_8;
        CData/*2:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__boothCode_9;
        CData/*2:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__boothCode_10;
        CData/*2:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__boothCode_11;
        CData/*2:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__boothCode_12;
        CData/*2:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__boothCode_13;
        CData/*2:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__boothCode_14;
        CData/*2:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__boothCode_15;
        CData/*1:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT____VdfgTmp_h78cd338f__0;
        CData/*0:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT____VdfgTmp_hb9e64110__0;
        CData/*1:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__div__DOT__state;
        CData/*3:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__div__DOT__counter;
        CData/*0:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__div__DOT__isDiv0;
        CData/*0:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__div__DOT__startFlag;
        CData/*0:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__div__DOT___T_3;
        CData/*0:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__div__DOT___T_9;
        CData/*3:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__div__DOT___T_31;
        CData/*0:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__div__DOT___T_33;
        CData/*3:0*/ top__DOT__core__DOT__EX_MEM__DOT__ff_lsuOp;
        CData/*0:0*/ top__DOT__core__DOT__EX_MEM__DOT__ff_reg_en;
        CData/*4:0*/ top__DOT__core__DOT__EX_MEM__DOT__ff_reg_addr;
        CData/*2:0*/ top__DOT__core__DOT__EX_MEM__DOT__ff_csr_op;
        CData/*0:0*/ top__DOT__core__DOT__EX_MEM__DOT__ff_csr_retired;
        CData/*3:0*/ top__DOT__core__DOT__EX_MEM__DOT__ff_excType;
    };
    struct {
        CData/*0:0*/ top__DOT__core__DOT__EX_MEM__DOT___T_3;
        CData/*0:0*/ top__DOT__core__DOT__MEM__DOT__wen;
        CData/*0:0*/ top__DOT__core__DOT__MEM__DOT__ren;
        CData/*1:0*/ top__DOT__core__DOT__MEM__DOT__width;
        CData/*0:0*/ top__DOT__core__DOT__MEM__DOT__ar_hs;
        CData/*0:0*/ top__DOT__core__DOT__MEM__DOT__r_hs;
        CData/*0:0*/ top__DOT__core__DOT__MEM__DOT__aw_hs;
        CData/*0:0*/ top__DOT__core__DOT__MEM__DOT__w_hs;
        CData/*0:0*/ top__DOT__core__DOT__MEM__DOT__b_hs;
        CData/*2:0*/ top__DOT__core__DOT__MEM__DOT__state;
        CData/*0:0*/ top__DOT__core__DOT__MEM__DOT___T_49;
        CData/*0:0*/ top__DOT__core__DOT__MEM__DOT___T_53;
        CData/*0:0*/ top__DOT__core__DOT__MEM__DOT___T_54;
        CData/*0:0*/ top__DOT__core__DOT__MEM__DOT___T_55;
        CData/*0:0*/ top__DOT__core__DOT__MEM__DOT___T_56;
        CData/*0:0*/ top__DOT__core__DOT__MEM__DOT___T_57;
        CData/*0:0*/ top__DOT__core__DOT__MEM__DOT__memAddr;
        CData/*0:0*/ top__DOT__core__DOT__MEM_WB__DOT__ff_reg_en;
        CData/*4:0*/ top__DOT__core__DOT__MEM_WB__DOT__ff_reg_addr;
        CData/*2:0*/ top__DOT__core__DOT__MEM_WB__DOT__ff_csr_op;
        CData/*0:0*/ top__DOT__core__DOT__MEM_WB__DOT__ff_csr_retired;
        CData/*0:0*/ top__DOT__core__DOT__MEM_WB__DOT___T_2;
        CData/*0:0*/ top__DOT__core__DOT__MEM_WB__DOT___T_3;
        CData/*0:0*/ top__DOT__core__DOT__regfile__DOT___T_4;
        CData/*0:0*/ top__DOT__core__DOT__resoler__DOT___T_2;
        CData/*0:0*/ top__DOT__core__DOT__resoler__DOT___T_10;
        CData/*0:0*/ top__DOT__core__DOT__resoler__DOT___T_35;
        CData/*0:0*/ top__DOT__core__DOT__ctrl__DOT___T;
        CData/*1:0*/ top__DOT__core__DOT__csr__DOT__mode;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT__mstatus_sum;
        CData/*1:0*/ top__DOT__core__DOT__csr__DOT__mstatus_mpp;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT__mstatus_spp;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT__mstatus_mpie;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT__mstatus_spie;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT__mstatus_mie;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT__mstatus_sie;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT__mie_meie;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT__mie_seie;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT__mie_mtie;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT__mie_stie;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT__mie_msie;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT__mie_ssie;
        CData/*1:0*/ top__DOT__core__DOT__csr__DOT__mtvec_mode;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT__mcause_int;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT__mipReal_seip;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT__mipReal_stip;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT__mipReal_ssip;
        CData/*1:0*/ top__DOT__core__DOT__csr__DOT__stvec_mode;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT__scause_int;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT__satp_mode;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT__mip_ssip;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT__mip_stip;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT__mip_seip;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT___T_267;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT__readable;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT__writable;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT___T_319;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT__hasIntM;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT__hasInt;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT__handIntS;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT__handExcS;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT___T_605;
        CData/*0:0*/ top__DOT__core__DOT__csr__DOT___GEN_67;
        CData/*0:0*/ top__DOT__core__DOT__arbiter__DOT__selectLsaxi;
    };
    struct {
        CData/*0:0*/ top__DOT__xbar__DOT___T_2;
        CData/*0:0*/ top__DOT__xbar__DOT___T_5;
        CData/*1:0*/ top__DOT__xbar__DOT__selectedReadSlave;
        CData/*0:0*/ top__DOT__xbar__DOT___T_9;
        CData/*0:0*/ top__DOT__xbar__DOT___T_12;
        CData/*1:0*/ top__DOT__xbar__DOT__selectedWriteSlave;
        CData/*0:0*/ top__DOT__xbar__DOT____VdfgTmp_hca0e4086__0;
        CData/*0:0*/ top__DOT__xbar__DOT____VdfgTmp_h777f794a__0;
        CData/*0:0*/ top__DOT__rom__DOT__state;
        CData/*0:0*/ top__DOT__rom__DOT__r_hs;
        CData/*0:0*/ top__DOT__rom__DOT___T_1;
        CData/*0:0*/ top__DOT__rom__DOT___GEN_0;
        CData/*0:0*/ top__DOT__ram__DOT__rHandshake;
        CData/*0:0*/ top__DOT__ram__DOT__bHandshake;
        CData/*2:0*/ top__DOT__ram__DOT__state;
        CData/*0:0*/ top__DOT__ram__DOT___T_1;
        CData/*0:0*/ top__DOT__ram__DOT___T_3;
        CData/*0:0*/ __Vtrigrprev__TOP__clock;
        CData/*0:0*/ __VactContinue;
        SData/*11:0*/ top__DOT__core__DOT__ID__DOT__immI;
        SData/*11:0*/ top__DOT__core__DOT__ID__DOT___T_840;
        SData/*11:0*/ top__DOT__core__DOT__ID_EX__DOT__ff_csrAddr;
        SData/*11:0*/ top__DOT__core__DOT__EX_MEM__DOT__ff_csr_addr;
        SData/*11:0*/ top__DOT__core__DOT__MEM_WB__DOT__ff_csr_addr;
        VL_OUT(io_inst,31,0);
        VL_OUT(io_pc,31,0);
        VL_OUT(io_npc,31,0);
        VL_OUT(io_flushpc,31,0);
        VL_OUT(io_wbinst,31,0);
        VL_OUT(io_bpuaddr,31,0);
        VL_OUT(io_idpc,31,0);
        VL_OUT(io_idinst,31,0);
        VL_OUT(io_expc,31,0);
        VL_OUT(io_exinst,31,0);
        VL_OUT(io_mempc,31,0);
        VL_OUT(io_meminst,31,0);
        VL_OUT(io_result,31,0);
        VL_OUT(io_waddr,31,0);
        VL_OUT(io_state,31,0);
        IData/*31:0*/ top__DOT__core__DOT__fetch_io_axi_master_rdata;
        IData/*31:0*/ top__DOT__core__DOT__ID_io_read1_data;
        IData/*31:0*/ top__DOT__core__DOT__ID_io_read2_data;
        IData/*31:0*/ top__DOT__core__DOT__MEM_io_except_excValue;
        IData/*31:0*/ top__DOT__core__DOT__MEM_io_mem_o_reg_data;
        IData/*31:0*/ top__DOT__core__DOT__arbiter_io_selectedMaster_master_awaddr;
        IData/*31:0*/ top__DOT__core__DOT__arbiter_io_selectedMaster_master_araddr;
        IData/*31:0*/ top__DOT__core__DOT__fetch__DOT__pc;
        IData/*31:0*/ top__DOT__core__DOT__fetch__DOT___T_8;
        IData/*31:0*/ top__DOT__core__DOT__IF_ID__DOT__ff_pc;
        IData/*31:0*/ top__DOT__core__DOT__IF_ID__DOT__ff_inst;
        IData/*31:0*/ top__DOT__core__DOT__IF_ID__DOT__ff_bpu_takepc;
        IData/*31:0*/ top__DOT__core__DOT__ID__DOT__inst;
        IData/*31:0*/ top__DOT__core__DOT__ID__DOT___GEN_1;
        IData/*31:0*/ top__DOT__core__DOT__ID__DOT__takepc;
        IData/*31:0*/ top__DOT__core__DOT__ID__DOT___T_849;
        IData/*31:0*/ top__DOT__core__DOT__ID__DOT____VdfgTmp_h6e65807c__0;
        IData/*31:0*/ top__DOT__core__DOT__ID_EX__DOT__ff_opr1;
        IData/*31:0*/ top__DOT__core__DOT__ID_EX__DOT__ff_opr2;
        IData/*31:0*/ top__DOT__core__DOT__ID_EX__DOT__ff_lsuData;
        IData/*31:0*/ top__DOT__core__DOT__ID_EX__DOT__ff_csrrData;
        IData/*31:0*/ top__DOT__core__DOT__ID_EX__DOT__ff_csrwData;
        IData/*31:0*/ top__DOT__core__DOT__ID_EX__DOT__ff_excValue;
        IData/*31:0*/ top__DOT__core__DOT__ID_EX__DOT__ff_inst;
        IData/*31:0*/ top__DOT__core__DOT__ID_EX__DOT__ff_currentPc;
    };
    struct {
        IData/*31:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul_io_mul1;
        IData/*31:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__div_io_divident;
        IData/*31:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__div_io_divisor;
        VlWide<3>/*64:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__div__DOT__result;
        IData/*31:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__div__DOT__lastDivident;
        IData/*31:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__div__DOT__lastDivisor;
        VlWide<3>/*64:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__div__DOT__divisor;
        VlWide<3>/*64:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__div__DOT__maxDivisor;
        VlWide<3>/*64:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__div__DOT___GEN_16;
        VlWide<3>/*66:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__div__DOT___GEN_24;
        IData/*31:0*/ top__DOT__core__DOT__EX_MEM__DOT__ff_lsuData;
        IData/*31:0*/ top__DOT__core__DOT__EX_MEM__DOT__ff_reg_data;
        IData/*31:0*/ top__DOT__core__DOT__EX_MEM__DOT__ff_csr_data;
        IData/*31:0*/ top__DOT__core__DOT__EX_MEM__DOT__ff_excValue;
        IData/*31:0*/ top__DOT__core__DOT__EX_MEM__DOT__ff_inst;
        IData/*31:0*/ top__DOT__core__DOT__EX_MEM__DOT__ff_currentPc;
        IData/*31:0*/ top__DOT__core__DOT__MEM_WB__DOT__ff_reg_data;
        IData/*31:0*/ top__DOT__core__DOT__MEM_WB__DOT__ff_csr_data;
        IData/*31:0*/ top__DOT__core__DOT__MEM_WB__DOT__ff_currentPc;
        IData/*31:0*/ top__DOT__core__DOT__MEM_WB__DOT__ff_inst;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_0;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_1;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_2;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_3;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_4;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_5;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_6;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_7;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_8;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_9;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_10;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_11;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_12;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_13;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_14;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_15;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_16;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_17;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_18;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_19;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_20;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_21;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_22;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_23;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_24;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_25;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_26;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_27;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_28;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_29;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_30;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT__regfile_31;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT___GEN_21;
        IData/*31:0*/ top__DOT__core__DOT__regfile__DOT___GEN_53;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT__medeleg_data;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT__mideleg_data;
        IData/*29:0*/ top__DOT__core__DOT__csr__DOT__mtvec_base;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT__mscratch_data;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT__mepc_data;
        IData/*30:0*/ top__DOT__core__DOT__csr__DOT__mcause_code;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT__mtval_data;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT___T_31;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT___T_47;
        IData/*29:0*/ top__DOT__core__DOT__csr__DOT__stvec_base;
    };
    struct {
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT__sscratch_data;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT__sepc_data;
        IData/*30:0*/ top__DOT__core__DOT__csr__DOT__scause_code;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT__stval_data;
        IData/*21:0*/ top__DOT__core__DOT__csr__DOT__satp_ppn;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT___T_74;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT___T_82;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT___T_83;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT___T_84;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT___T_92;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT___T_94;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT___T_129;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT___T_130;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT___T_142;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT___T_235;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT___T_422;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT__csrData;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT___T_510;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT___T_512;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT__writeData;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT__flagIntS;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT__flagIntM;
        IData/*30:0*/ top__DOT__core__DOT__csr__DOT__intCauseS;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT__cause;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT___T_675;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT___T_717;
        IData/*31:0*/ top__DOT__core__DOT__csr__DOT___T_756;
        IData/*31:0*/ top__DOT__rom__DOT__readModule__DOT__fetched_data;
        IData/*31:0*/ top__DOT__ram__DOT__awrite_rdata;
        IData/*31:0*/ __Vfunc_vaddr_read__4__Vfuncout;
        IData/*31:0*/ __VstlIterCount;
        IData/*31:0*/ __VicoIterCount;
        IData/*31:0*/ __VactIterCount;
        QData/*62:0*/ top__DOT__core__DOT__EX__DOT__result;
        QData/*63:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul_io_result;
        QData/*63:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mulOut;
        QData/*63:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_io_A;
        QData/*63:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_io_B;
        QData/*63:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_io_Cin;
        QData/*63:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_1_io_A;
        QData/*63:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_1_io_B;
        QData/*63:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_1_io_Cin;
        QData/*63:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_2_io_A;
        QData/*63:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_2_io_B;
        QData/*63:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_2_io_Cin;
        QData/*63:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_3_io_A;
        QData/*63:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_3_io_B;
        QData/*63:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_3_io_Cin;
        QData/*63:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_4_io_A;
        QData/*63:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_4_io_B;
        QData/*63:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_4_io_Cin;
        QData/*63:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_5_io_A;
        QData/*63:0*/ top__DOT__core__DOT__EX__DOT__mdu__DOT__mul__DOT__CarrySaveAdder_5_io_B;
        QData/*63:0*/ top__DOT__core__DOT__csr__DOT__mcycle_data;
        QData/*63:0*/ top__DOT__core__DOT__csr__DOT__minstret_data;
        QData/*63:0*/ top__DOT__core__DOT__csr__DOT___T_617;
        QData/*63:0*/ top__DOT__core__DOT__csr__DOT___T_619;
        QData/*63:0*/ top__DOT__core__DOT__csr__DOT___T_762;
        QData/*63:0*/ top__DOT__core__DOT__csr__DOT___T_765;
        QData/*63:0*/ top__DOT__core__DOT__csr__DOT___T_768;
        QData/*63:0*/ top__DOT__core__DOT__csr__DOT___T_771;
        VlUnpacked<CData/*0:0*/, 3> __Vm_traceActivity;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<1> __VactTriggered;
    VlTriggerVec<1> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
